# .travis.yml

language: python
python: 
  - "2.7"
  - "3.6"
cache: pip
dist: xenial
install:
  - pip install lint codecov incremental
script:
  - python pgtree/pgtree.py
  - pylint pgtree/pgtree.py ; echo done
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then exit 0; fi
  - python -m unittest discover -s tests/
  - coverage run tests/test_pgtree.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
